# Generated by Django 4.2.1 on 2023-06-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_category_remove_post_image_url_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='image',
            name='alt',
            field=models.CharField(default=None, max_length=30, verbose_name='Alternative text'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is Default'),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=None, max_length=30, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='contents.category'),
        ),
    ]
