# Generated by Django 4.2.1 on 2023-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Fullname')),
                ('user_name', models.CharField(db_index=True, help_text='Username to login and show in the profile', max_length=150, unique=True, verbose_name='User_Name:')),
                ('password', models.IntegerField(help_text='Password to login', verbose_name='Password:')),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to='uploads/photos/', verbose_name='Image:')),
                ('bio', models.TextField(verbose_name='Biography:')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth_date:')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('join_date', models.DateTimeField(verbose_name='Join_date:')),
            ],
        ),
    ]
